title: pix2pix Colorization
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://Ha-eunYu.github.io/pix2pix_Colorization

aux_links:
  Ha-eunYu: https://github.com/Ha-eunYu/pix2pix Colorization

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
